# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d5eefc1f590617384de0ac39143bed827178f12f4e6ac259dff8b0a0d54a8cc74f686b8d05f9cf94f3a73d88a134e4290f88f32b351b801eb11e5cf0fa398a9

test:
  secret_key_base: 5080d9b2d532735ba0cc672065cf647986ff0e36fb19aa5953ae4cccbeb68e045f6c4d9f0c82681719a5053de1ad1c0016092b696cde26d7ac2a6fc8a4a25e3a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
